dist: trusty
sudo: required


services:
  - docker

language: java
jdk: oraclejdk8

env:
  global:
    - secure: "lwJXtk9yJCHqZIkiEP5u+mP7mn2tatrCUzAxhzMQ4PaCacxrnnTsK+C7jWb6Um+TA7M3F1LLTEqjzrbcEAb2mIsAxxJsoPphoCK1ZORVjFglJB1lVOF0qXK8rQk05hEFuCLjpz4ZtJ8Kd0/67fN69jsW1WMXkELz6f6yMfaap+qL+JsKRGzScFajbNI/dnxfcx+EyJdGj8RcvEfi3dM7reU7Hi0QcVwjbBswfS3rqUPT8/m5UJ4PruC/enzZR42HAMgpzDArJg2dEgicb64G4TTyDwhUH5Lp8S3jbeiALIyZyQx3LmtUW43jkOGskXYo8KQFdWu8fHSXb5NkTuGiZHCwiz/vb6XERu2aZV7cXekSLDxKMw3haiVQsJpSYGkInklRZ6tfygbVwjmGDofu2x/FMRqsq3eb9v/gjUOX9lKXlILymst60QoeLSkADbhIEcpwekxoMILdxJGf2/s8u4vM+oOLhmqAqTOe98+sjgn70sDSpDHdwHtqHiTT8DT5MU5DWbiEzJmPU42HBjjmo5J0IX0hGL9WLLhSgTBfnGQUThf4ywYqp+NlTj5T+K3Q5xRKNX7q0C/A83B+sFrdZsseF0fVjzK2BUqbC+Z+fZVOXc40usQi37HpEzsB6eRI15ZaxmsbwluFhqEr+oQHJOCwXOvfZPJ2nj2S1n5hJ/k="
    - secure: "q0+rR8yML7Po3too0vazq8cbYFm8061o1on26DZxWZo+hhtU/qbX5laPc92xHoh9HeOAWkg+MvOm37hAK8AJoSR4MZDWgLjHX6z1mlsNYiNS0/Q+Fh2fgqUsuH0diPvj0fKpVH2EyavwwZDo7McxnLOA19X62Utv4jZCRRzqsrmN/ux/PJRRWOvvRB/1kHT2yLfA68h5XMHfYLiSsrnAkmuwzeM0tdCShtHvLe+o0mdG9xn68LKaxv5ATly/J4MP7hkLC1J3fX2Dmkpu3jPnrvrL91Rkc0t83vhikZ/VbB8N+s65bq+bqzIUQoe2v66BiE+QTJ/qZtxPM/gu0332LcEz1dVpwPpO9dL1t+G5+sFH4mMVLnDXWUulxDmvujTAbKT+6s7QW3sHFWtRaoihqezqUMeAeNJ6He2T0RF/gIxVX5uDyptOmyNv6LZcFF/fuVqffgCRuoWruH75dcXZKWDImgQ1si5vd0JwUU/CXlBSz3fEBVpWKGnMWeBxHY9ahAEWL3E1mNrGamgdv6Ll1s94+jqrKv7n1QplPOqUbYMEge/ti5P0DEADrFwxKyPT7+dXdOe3TPSxCZJjK4jTdgaIkR5HmI4JKBofPdXmnCfvLKIlTj66lJlbkInrN3/CGhj2jrMYEvRClgodApz2NOcn3dWBxoo4vVC7FmmCi44="
    - COMMIT=${TRAVIS_COMMIT::7}

after_success:
  - bash <(curl -s https://codecov.io/bash)
  - docker login -u $DOCKER_USER -p $DOCKER_PASS

  #TAG
  - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`

  # CONFIG SERVICE
  - export CONFIG=nibali/piggymetrics-config
  - docker build -t $CONFIG:$COMMIT ./config
  - docker tag $CONFIG:$COMMIT $CONFIG:$TAG
  - docker push $CONFIG

  # REGISTRY
  - export REGISTRY=nibali/piggymetrics-registry
  - docker build -t $REGISTRY:$COMMIT ./registry
  - docker tag $REGISTRY:$COMMIT $REGISTRY:$TAG
  - docker push $REGISTRY

  # GATEWAY
  - export GATEWAY=nibali/piggymetrics-gateway
  - docker build -t $GATEWAY:$COMMIT ./gateway
  - docker tag $GATEWAY:$COMMIT $GATEWAY:$TAG
  - docker push $GATEWAY

  # AUTH SERVICE
  - export AUTH_SERVICE=nibali/piggymetrics-auth-service
  - docker build -t $AUTH_SERVICE:$COMMIT ./auth-service
  - docker tag $AUTH_SERVICE:$COMMIT $AUTH_SERVICE:$TAG
  - docker push $AUTH_SERVICE

  # ACCOUNT SERVICE
  - export ACCOUNT_SERVICE=nibali/piggymetrics-account-service
  - docker build -t $ACCOUNT_SERVICE:$COMMIT ./account-service
  - docker tag $ACCOUNT_SERVICE:$COMMIT $ACCOUNT_SERVICE:$TAG
  - docker push $ACCOUNT_SERVICE

  # STATISTICS SERVICE
  - export STATISTICS_SERVICE=nibali/piggymetrics-statistics-service
  - docker build -t $STATISTICS_SERVICE:$COMMIT ./statistics-service
  - docker tag $STATISTICS_SERVICE:$COMMIT $STATISTICS_SERVICE:$TAG
  - docker push $STATISTICS_SERVICE

  # NOTIFICATION_SERVICE
  - export NOTIFICATION_SERVICE=nibali/piggymetrics-notification-service
  - docker build -t $NOTIFICATION_SERVICE:$COMMIT ./notification-service
  - docker tag $NOTIFICATION_SERVICE:$COMMIT $NOTIFICATION_SERVICE:$TAG
  - docker push $NOTIFICATION_SERVICE

  # MONITORING
  - export MONITORING=nibali/piggymetrics-monitoring
  - docker build -t $MONITORING:$COMMIT ./monitoring
  - docker tag $MONITORING:$COMMIT $MONITORING:$TAG
  - docker push $MONITORING

  # TURBINE STREAM SERVICE
  - export TURBINE=nibali/piggymetrics-turbine-stream-service
  - docker build -t $TURBINE:$COMMIT ./turbine-stream-service
  - docker tag $TURBINE:$COMMIT $TURBINE:$TAG
  - docker push $TURBINE

  # MONGO DB
  - export MONGO_DB=nibali/piggymetrics-mongodb
  - docker build -t $MONGO_DB:$COMMIT ./mongodb
  - docker tag $MONGO_DB:$COMMIT $MONGO_DB:$TAG
  - docker push $MONGO_DB
